spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1041232514862-pidc952364quk94imvncomlqqmkvrr9i.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
